"""
Django settings for medical_website project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    'SECRET_KEY',
    default='django-insecure-ex19_c$+hcm#&#xq*6-0h-pa5x&7m*&drixp%r)517wzun$400',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Railway injects the app's public domain in this env var; accept it
# automatically so ALLOWED_HOSTS doesn't need to be kept in sync by hand.
RAILWAY_PUBLIC_DOMAIN = env.str('RAILWAY_PUBLIC_DOMAIN', default='')
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'clinics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# React dev servers (Create React App / Vite) hitting this API locally, by
# default. Override/extend via the comma-separated CORS_ALLOWED_ORIGINS env
# var to add production frontend origin(s) without a code change.
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
])

ROOT_URLCONF = 'medical_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'medical_website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Railway provisions Postgres and injects DATABASE_URL automatically; falls
# back to local SQLite when it's unset (local dev).

DATABASES = {
    'default': env.db('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Railway's filesystem is ephemeral — anything written to MEDIA_ROOT (e.g.
# Doctor.photo uploads) is lost on every redeploy/restart. Setting
# AWS_STORAGE_BUCKET_NAME switches the default file storage to S3 (or any
# S3-compatible provider, via AWS_S3_ENDPOINT_URL) so uploads persist; with
# it unset, local dev keeps using the filesystem unchanged.
AWS_STORAGE_BUCKET_NAME = env.str('AWS_STORAGE_BUCKET_NAME', default='')

STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage'
        if AWS_STORAGE_BUCKET_NAME
        else 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if AWS_STORAGE_BUCKET_NAME:
    AWS_ACCESS_KEY_ID = env.str('AWS_ACCESS_KEY_ID', default='')
    AWS_SECRET_ACCESS_KEY = env.str('AWS_SECRET_ACCESS_KEY', default='')
    AWS_S3_REGION_NAME = env.str('AWS_S3_REGION_NAME', default='')
    # Optional: point at an S3-compatible provider (Cloudflare R2, Backblaze
    # B2, DigitalOcean Spaces, Railway's bucket offering) instead of AWS.
    AWS_S3_ENDPOINT_URL = env.str('AWS_S3_ENDPOINT_URL', default='') or None
    # Optional: serve media through a CDN/custom domain instead of the raw
    # bucket/endpoint URL.
    AWS_S3_CUSTOM_DOMAIN = env.str('AWS_S3_CUSTOM_DOMAIN', default='') or None
    AWS_DEFAULT_ACL = None  # bucket-policy-controlled access, not object ACLs
    AWS_S3_FILE_OVERWRITE = False  # don't clobber same-named uploads

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # 'assistant' scope throttles the public AI chat endpoint, which is
    # unauthenticated (AllowAny) and each request calls the paid OpenAI API
    # — without a rate limit it's an open cost/abuse vector.
    'DEFAULT_THROTTLE_RATES': {
        'assistant': '20/hour',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Medical Clinics API',
    'DESCRIPTION': 'Public API for browsing clinics/services/doctors and booking appointments.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
