# Generated by Django 6.1 on 2026-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'preferred_date', 'preferred_time'], name='clinics_appt_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='clinics_appt_status_idx'),
        ),
    ]
