# Generated by Django 6.1 on 2026-08-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_appointment_options_alter_clinic_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='clinics_appt_slot_idx',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('doctor', 'preferred_date', 'preferred_time'), name='clinics_appt_slot_uniq'),
        ),
    ]
